### ISSUE TITLE
Not the First Work

### ISSUE THREAD

**Issue by a-arnold66** [saltoricristiano/cosmix-uda#1]
This is definitely NOT "_the first using compositional mix between domains to allow adaptation in LiDAR segmentation_". I have seen ideas like this half a year ago, for example, the following: 

ConDA: Unsupervised Domain Adaptation for LiDAR Segmentation via Regularized Domain Concatenation
https://arxiv.org/pdf/2111.15242.pdf

**Comment by saltoricristiano** [comment]
Hi @a-arnold66, 

thanks for pointing out this discussion!

Firstly, we were unaware of your method.
We took some time to read through your paper and these are our considerations.

ConDA has interesting ideas but we think it may not be considered as the first LiDAR mix-based method for UDA in LiDAR segmentation. Let me better explain why in the following points:

1. ConDA uses range views (RVs) that are the 2D cylindrical projection of the 3D LiDAR signal, which after projection on the image plane, 2D RVs can be processed with conventional deep networks for 2D data. This means that their architecture is a 2D network which takes a 2D image-like input and does not process the "raw" 3D signal captured by the LiDAR sensor. Therefore, any existing UDA method for 2D segmentation could be applied. We could not find any specific re-formulation of 2D mixing for 3D data in ConDA.

2. Focusing on the mixing part, ConDA applies a modification of CutMix (https://arxiv.org/abs/1905.04899) on pre-defined 2D range regions, and mixes the source and target domains by copy pasting patches of images. This is a well known practice and has been already used in the 2D UDA literature (https://openaccess.thecvf.com/content/WACV2021/papers/Tranheden_DACS_Domain_Adaptation_via_Cross-Domain_Mixed_Sampling_WACV_2021_paper.pdf). Also in this case, it would be difficult to apply their mixing strategy on 3D data as they have often empty regions/voxels.

3. The experimental part does not include a direct comparison with recent LiDAR based UDA approaches like PCT (https://arxiv.org/abs/2107.05399) and it is limited only on the nuScenes domain (Boston/Singapore).

Secondly, according to the current rules in our community, if a manuscript has not been published through a peer-review process, one is not obliged to cite it (https://cvpr2022.thecvf.com/author-guidelines).

Please let us know what do you think in the comments!

**Comment by saltoricristiano** [comment]
Hi @a-arnold66, 

Due to inactivity in this issue, I'm going to close the issue.
Feel free to open a new one in case of other questions.
@saltoricristiano

**Comment by a-arnold66** [comment]
Hi @saltoricristiano,

I am a practitioner as well as a researcher in the field of semantic scene mapping of autonomous driving. For your previous answers, I would like to point out some issues:

1. The range view projection of LiDAR point clouds embed 3D information, such as point coordinates (x, y, z), intensity (remission), and depth. Therefore, it preserves the spatial layouts of 3D scenes. Mixing happens in the range image reflecting that the original points are also mixed. I would suggest you read the [RangeNet++ paper](http://www.ipb.uni-bonn.de/wp-content/papercite-data/pdf/milioto2019iros.pdf) for a more clear understanding. 
2. In the ConDA paper, the authors mix points in a structural manner, i.e., the mixing is conducted along the row and column of the range image, which corresponds to the inclination and azimuth of the point clouds. Besides, the authors have compared the unstructured CutMix mixing and proven their superiority.
3. The ConDA paper targets cross-city UDA, where only nuScenes contains data like this.
4. According to the rule of the community, an arXiv paper that came out recently (e.g., two or three months) will not need to be compared. However, the ConDA paper came out in Nov 2021. I believe a practitioner which is highly active in this area will have already seen relevant papers more than half a year ago.

Personally, I believe both of your ideas are great. As a practitioner, I am glad to see methods that are simple and effective. I hope every research work that the authors have put effort into should be treated fairly.
