### ISSUE TITLE
Can Synthetic data point cloud converted to real data point cloud with cosmix for segmentation

### ISSUE THREAD

**Issue by vijayM12** [saltoricristiano/cosmix-uda#12]
Hello @saltoricristiano I have read the Cosmix based on synLiDAR datset to semantickitti. I am working on synthetic data to real data point cloud translation and could not find the repo for "Transfer Learning from Synthetic to Real LiDAR Point Cloud for Semantic Segmentation". I would like to know if you have the idea on PCT algorithm of syn2real (Synlidar to semantickitti conversion) or can we do that using your present work Cosmix. (My research is on syn2real conversion). If you have the converted .bin files from synthetic to realistic data please help me since my research work needs the converted point cloud files.

**Comment by saltoricristiano** [comment]
Hi @vijayM12, 

thanks for the interest in our work!
You can find the official repository of PCT [here](https://github.com/xiaoaoran/SynLiDAR). However, it seems they still have to release the code. Since the code is not avaliable, we used the same configurations of PCT and compared with their results.
So, no we don't have the converted synthetic 2 real data :(
Let me know if I solved your issue!
@saltoricristiano

**Comment by vijayM12** [comment]
> Hi @vijayM12,
> 
> thanks for the interest in our work! You can find the official repository of PCT [here](https://github.com/xiaoaoran/SynLiDAR). However, it seems they still have to release the code. Since the code is not avaliable, we used the same configurations of PCT and compared with their results. So, no we don't have the converted synthetic 2 real data :( Let me know if I solved your issue! @saltoricristiano

So can we use cosmix in place of PCT for segmentation purpose? Any idea of how to convert synthetic to real data

**Comment by saltoricristiano** [comment]
No, cosmix can be used for domain adaptation from syntetic to real. Cosmix is not a generative approach, so we don't convert synthetic data in the real domain. In your case, I would opend an issue in PCT asking for the implementation or asking for support in a possible re-implementation. If conversion is your only goal and you don't care about reproducing PCT,  "Domain Transfer for Semantic Segmentation of LiDAR Data using Deep Neural Networks" https://github.com/PRBonn/lidar_transfer uses meshing for converting data from one sensor modality to another.
I hope I helped you 👍

**Comment by vijayM12** [comment]
> No, cosmix can be used for domain adaptation from syntetic to real. Cosmix is not a generative approach, so we don't convert synthetic data in the real domain. In your case, I would opend an issue in PCT asking for the implementation or asking for support in a possible re-implementation. If conversion is your only goal and you don't care about reproducing PCT, "Domain Transfer for Semantic Segmentation of LiDAR Data using Deep Neural Networks" https://github.com/PRBonn/lidar_transfer uses meshing for converting data from one sensor modality to another. I hope I helped you 👍

Yes conversion from synLiDAR point clouds data to semantic kitti point cloud data is my goal. Can the given reference implementation be used to convert point cloud files? Because I am aware of converting labels of synlidar wrt semantickitti. But, point cloud translation of synLidar to semantic kitti using GAN is my main goal and I am not sure how to do it without any reference implementation code

**Comment by saltoricristiano** [comment]
Hi @vijayM12 ,

yes the method in https://github.com/PRBonn/lidar_transfer can be used to convert point clouds between modalities but by meshing and ray casting. I don't know any existing paper with code using GANs.

**Comment by vijayM12** [comment]
> Hello @saltoricristiano I was trying to reproduce the https://github.com/PRBonn/lidar_transfer repo and facing issue while running make. Could you please guide me in executing the repo . The error is as below
![error1](https://user-images.githubusercontent.com/93333400/208293100-5a54ddc3-24cd-4e68-bf35-4a8aa631c663.png)
![error ](https://user-images.githubusercontent.com/93333400/208293104-dd3dcc27-0fb9-4b55-b53f-0e310884d158.png)
