### ISSUE TITLE
different dataset

### ISSUE THREAD

**Issue by mofarazi** [saltoricristiano/cosmix-uda#14]
Hi,

Thanks for the awesome work and provided code! I was wondering if I can use another dataset like NuScenes, PandaSet, or my own custom dataset (no labels) for the adaption process. Let's say I have pretrained model on semanticKITTI and another LiDAR dataset which is not labeled, can I still use this code?

**Comment by saltoricristiano** [comment]
Hi @mofarazi,

thanks for the interest in our work!
While we didn't apply our method on other datasets, you can use our work on any dataset! You will need to modify a bit the code and implement your own dataset classes, but the rest should work!
Roughly speaking, the steps I foresee are:

1. implementation of the dataset classes (as done for the already implemented datasets e.g. [SemanticKITTI](https://github.com/saltoricristiano/cosmix-uda/blob/b15f4cec948e6d13c305b21f7fcb8ce6dcdb94e1/utils/datasets/semantickitti.py#L13))
2. find a common class mapping and put it into a file. For example [here](https://github.com/saltoricristiano/cosmix-uda/blob/b15f4cec948e6d13c305b21f7fcb8ce6dcdb94e1/utils/datasets/_resources/synlidar_semantickitti.yaml#L37) we provide a common mapping for synlidar to semantickitti. This mapping will be used to map classes in the dataset ([here](https://github.com/saltoricristiano/cosmix-uda/blob/b15f4cec948e6d13c305b21f7fcb8ce6dcdb94e1/utils/datasets/semantickitti.py#L179))
3. warm up the model on the source dataset
4. apply CoSMIX!

I hope you will find my suggestions useful!
@saltoricristiano
