### ISSUE TITLE
question about loading model

### ISSUE THREAD

**Issue by NoName5990** [saltoricristiano/cosmix-uda#15]
Hello, @saltoricristiano ,
Thanks for the awesome work and provided code! I found a question when I run the`eval.py` . At the line 42 , the function `clean_state_dict()` does not seem to use the `state` parameter but the `ckpt`, so I should replace the ckpt with state?
```
def load_model(checkpoint_path, model):
    # reloads model
    def clean_state_dict(state):
        # clean state dict from names of PL
        for k in list(ckpt.keys()):
            if "model" in k:
                ckpt[k.replace("model.", "")] = ckpt[k]
            del ckpt[k]
        return state

    ckpt = torch.load(checkpoint_path, map_location=torch.device('cpu'))["state_dict"]
    ckpt = clean_state_dict(ckpt)
    model.load_state_dict(ckpt, strict=True)
    return model
```

**Comment by saltoricristiano** [comment]
Hi @NoName5990, 

thanks for your interest in our work!
Thanks for pointing out the small imprecision. The function modifies locally ckpt from the main function, state points to ckpt and ckpt's keys are modified in the for loop. As a result, what the function returns is still state=ckpt with modified keys.
The result is the same and ckpt keys are cleaned but, I agree and apologize, codewise it's not very clear 👍 

Let me know if everything is clear and if I solved your doubts!
@saltoricristiano

**Comment by NoName5990** [comment]
> Hi @NoName5990,
> 
> thanks for your interest in our work! Thanks for pointing out the small imprecision. The function modifies locally ckpt from the main function, state points to ckpt and ckpt's keys are modified in the for loop. As a result, what the function returns is still state=ckpt with modified keys. The result is the same and ckpt keys are cleaned but, I agree and apologize, codewise it's not very clear 👍
> 
> Let me know if everything is clear and if I solved your doubts! @saltoricristiano

Hi @saltoricristiano,

Thank you for your response and clarification regarding the code. I appreciate your explanation. It's clear to me now.

@NoName5990
