### ISSUE TITLE
About alpha in Section3.1 in paper

### ISSUE THREAD

**Issue by zou-longkun** [saltoricristiano/cosmix-uda#3]
Hello, I did not understand the alpha parameter in Equation 1 in Section 3.1 of the paper, does it mean that only the top 50% low-frequency classes are selected？

**Comment by saltoricristiano** [comment]
Hi @zou-longkun, 

thanks for your interest in our work!
In Eq. 1 we perform a weighted random sampling of alpha classes implemented [here](https://github.com/saltoricristiano/cosmix-uda/blob/64ee70258ddd66c1341d2d4446fc0dcbe6472ee7/utils/pipelines/masked_simm_pipeline.py#L145). 

With alpha=0.5 we perform a weighted random sampling of 50% of the classes based on the inverse of their frequency distribution (i.e. the highest the frequency, the lower the weight). Therefore, also the most frequent classes have the probability - even if low - to be selected. Indeed, if you check the qualitative results  of Fig. 1-2 in the Supp. Mat. , you will see that also high frequency classes (building, road an so on) are sometimes selected.

Did I solve all your doubts?
@saltoricristiano
