### ISSUE TITLE
TypeError: Can't instantiate abstract class PLTTrainer with abstract methods forward

### ISSUE THREAD

**Issue by Stone-sy** [saltoricristiano/cosmix-uda#4]
![image](https://user-images.githubusercontent.com/52024213/188618140-fe2033e3-2b9f-4386-866f-959498a58ef7.png)

**Comment by saltoricristiano** [comment]
Hi @Stone-sy, 

can you give me some additional info about your run?
Other people have been able to use the code without problems, which version of pytroch-lighting are you using?
Have you tried to use the docker container? And, did you already solve the issue?

Thx!

**Comment by Stone-sy** [comment]
您好！您的邮件我已收到！

**Comment by saltoricristiano** [comment]
Hi, 

sorry but I cannot help you without additional information about your system.
can you give me some additional info about your run?
Other people have been able to use the code without problems, which version of pytroch-lighting are you using?
Have you tried to use the docker container? And, did you already solve the issue?

Thx

**Comment by Stone-sy** [comment]
I changed the version of pytorch lighting to solve the problem. Thank you！
