### ISSUE TITLE
Usage of intensity for experiments with  SynLiDAR ? 

### ISSUE THREAD

**Issue by BjoernMichele** [saltoricristiano/cosmix-uda#5]
Dear @saltoricristiano , 

Thank you very much for your interesting work and providing the code. 

As SynLiDAR provides intensities, I would just check back with you if they are used as features in the UDA setting with SemanticKITTI ? 

Secondly, I was wondering, as the results you report for Source, ADDA, Ent-Min  , ST, PCT, ST-PCT in the SynLiDAR to SemanticKITTI scenario are partly exactly the same as in the paper of SynLiDAR, sometimes slightly different, if you have redone their experiments or if  the results are based on their paper ?  

With best regards, 
Bjoern

**Comment by saltoricristiano** [comment]
Hi @BjoernMichele, 

thank you for your interest in our work!
We do not use intensity values as we did not notice any significant difference in using it.
Regarding the results, I guess you refer to Ent-Min and ADDA results. We did notice some errors in the mean results in the SynLIDAR paper. If you compute the average of the per-class IoU, you will get our numbers.
All the baseline results are taken from the SynLiDAR paper as reported in the Experimental Section.

Please let me know if I solved all your doubts 👍

**Comment by BjoernMichele** [comment]
Thank you very much for your fast reply. Everyhting solved :)
