### ISSUE TITLE
synlidar2semantickitti_correct.npy

### ISSUE THREAD

**Issue by Stone-sy** [saltoricristiano/cosmix-uda#7]
Hello, how are the parameters in `synlidar2semantickitti_correct.npy` calculated?

**Comment by saltoricristiano** [comment]
Hi @Stone-sy!

thanks for your interest in our work!

You can find [here](https://github.com/saltoricristiano/cosmix-uda/blob/20563ee0fd7504fc2b6a00b11af4dab1343d85f6/utils/datasets/semanticposs.py#L162) the function used to get the weights.

Let me know if this helped! 👍 
Cheers, 
saltoricristiano

**Comment by Stone-sy** [comment]
您好！您的邮件我已收到！
