### ISSUE TITLE
Evaluation protocoll

### ISSUE THREAD

**Issue by BjoernMichele** [saltoricristiano/cosmix-uda#9]
Hello @saltoricristiano , 

I have just a few questions to make sure I understand it right what you use as evaluation in the EVAL.py: 

1.  You make the comparison on the voxel level, so you don't project the predictions and lables  back to the individual points as I could not found such a projection in the code. (probably with a voxel size of 0.05 there is not too much difference but for larger voxel sizes I could imagine there could be a difference). 
2. Do I understand the evaluation step (in the test_step function) correctly:  you calculate the mIoU of each class for the scenes of the batch, and to calculate the final mIoU you average the results for each class the mIoU of the scenes this class appears.

Another thing I would like check back with you: when I retrained out of the shelf your Warm-Up for SynLiDAR to SemanticKITTI I reached a performance of 25.9% mIoU. Knowing that there could be a lot of variation in UDA, I am wondering if to your knowledge this lays in the  range of variation (as you start from a source performance of 20.4 % mIoU), and I can start the adaption phase on that, or if I did perhaps something wrong. 

Have a great day,
Best, 
Bjoern

**Comment by saltoricristiano** [comment]
Hi @BjoernMichele, 

thx again for your interest in our work!
In order:

1. yes, as our voxel size is 0.05, we do not re-project predictions. As you said, with bigger voxel sizes it may be required.
2. yes, first per-class IoU and then average over the classes. This is the only way to obtain a table where class IoU and mIoU can be shown side-by-side.
3. the source results are obtained from the SynLiDAR paper. Following author instructions we have been able to reproduce their numbers in all the settings. However, during the CoSMix warm-up the random augmentations, init and different parameters may lead to a better generalization capability. I guess your numbers are in line with the range of variation you can have.

For other info feel free to message me also privately following my email if needed!

Best regards, 
Cristiano Saltori

**Comment by BjoernMichele** [comment]
Dear @saltoricristiano , 
Thank you for your answers, they help a lot :)  

Regarding the calculation of the per-class IoU, I am a bit concerned about rare classes e.g. Bicycle in SK: They have quite a large range of per scene frequency from just a few points to several bikes in one scene. With averaging the mIoU of these scenes, the  points of the same class from different scenes have a different impact onto the averaged IoU of a class.  For me it looks more natural, if each point count equally no matter in which scene it appears.
As you reproduced the Synthtetic LiDAR numbers, I assume they also used this protocoll ?

Best regards,
Bjoern

**Comment by yuan-zm** [comment]
I think we should follow the semanticKITTI official evaluation protocol. The IoU should calculate at the point-level.

**Comment by saltoricristiano** [comment]
Hi @dream-toy,

Yes sure, the evaluation protocol is the same, just we do not project predictions to the "unvoxelized" points.
I guess in our case re-projecting may be useless because:
- We have a very small voxel size
- All the other approaches in the tables did the same
- I tried months ago to re-project, it's a few lines of code, but without significant changes in the results (I guess it's due to the small voxel size we use)
- We don't won't to compare our performance to the official SemanticKITTI page as our task is UDA, not supervised 3D segmentation. As long as all the methods in the tables use the same evaluation protocol, everything is fair 😊

Please let me know if I solved all your doubts!

**Comment by yuan-zm** [comment]
Ok, Thank you for your reply. My doubts are solved.
